// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"play-together/config"
	"play-together/internal/routes"
	"play-together/internal/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig := config.LoadConfig()
	firebaseClient, err := config.NewFirebaseClient(configConfig)
	if err != nil {
		return nil, err
	}
	engine := routes.SetupRouter(firebaseClient)
	string2 := providePortFromConfig(configConfig)
	serverServer := server.NewServer(engine, string2)
	return serverServer, nil
}

// wire.go:

func providePortFromConfig(cfg *config.Config) string {
	return cfg.Port
}
